### PR TITLE
Updated header style and fixed a small bug in forms.less.

### PR DESCRIPTION
**Pull request by egdelwonk**

### CODE REVIEW

**Comment by egdelwonk** [comment]
screen shot 2014-01-31 at 10 00 49 pm

**Comment by jnoller** [comment]
THANK YOU!

**Comment by egdelwonk** [comment]
No problem! If you need any more help feel free to let me know. I'd love to be of any assistance I can.

**Comment by egdelwonk** [comment]
Hey Jesse, did you ever get around to deploying this?

**Comment by jnoller** [comment]
done!

**Comment by egdelwonk** [comment]
Sweet!

**Pull request merged**
