### PR TITLE
Use Markdown to improve readability

### PR DESCRIPTION
**Pull request by suriyaa**
Hi,

this is my first `getpython3.com` pull request! 😄

--[**Suriyaa Sundararuban**](https://about.suriyaa.tk/) *([My Python profile](https://www.python.org/users/suriyaa/)) ([My Bugs Profile](https://bugs.python.org/user28717))*

### CODE REVIEW

**Comment by suriyaa** [comment]
ping @jnoller

**Comment by jnoller** [comment]
I don't own or maintain this repo / domain/etc any longer.

**Comment by suriyaa** [comment]
@jnoller Ok.

ping instead @akuchling

**Comment by akuchling** [comment]
@jnoller I don't think we ever actually got it transferred to me, did we?  I don't think I know where it's hosted, for example.

**Pull request closed without merging**
